<?php

namespace App\Service;

use App\Entity\Company;
use App\Entity\CompanyRole;
use App\Entity\User;
use App\Repository\CompanyRepository;
use Doctrine\ORM\EntityManagerInterface;

/**
 * Service per la gestione centralizzata delle Company (Patroni, Banche, Fornitori).
 * Implementa i principi SOLID eliminando la duplicazione della logica di riconoscimento e creazione.
 */
class CompanyManager
{
    public function __construct(
        private readonly EntityManagerInterface $em,
        private readonly CompanyRepository $companyRepository,
        private readonly NormalizationService $normalizationService,
        private readonly \App\Service\Cube\NameGeneratorService $nameGenerator
    ) {}

    /**
     * Cerca una Company esistente tramite ricerca elastica (canonical) o ne crea una nuova automatica.
     * 
     * @param string $name Il nome visualizzato (es. "Baron Thorne")
     * @param User $user L'utente proprietario della campagna
     * @param CompanyRole $role Il ruolo (Patron, Bank, etc.)
     * @return Company L'entità trovata o appena creata (già persisita in Doctrine)
     */
    public function findOrCreateAuto(string $name, User $user, CompanyRole $role): Company
    {
        // 1. Normalizzazione per ricerca elastica
        $canonical = $this->normalizationService->normalize($name);

        // 2. Ricerca nel repository
        $company = $this->companyRepository->findOneByCanonicalName($canonical, $user, $role->getCode());

        // 3. Se non esiste, creazione automatica
        if (!$company) {
            $company = new Company();
            $company->setName($name);
            $company->setCompanyRole($role);
            $company->setUser($user);
            $company->setIsAutoGenerated(true);

            // Dati di default tipici per record autogenerati dalla console
            $contactName = $this->nameGenerator->generateForPatron('');
            $company->setContact($contactName);
            $company->setSignLabel($contactName);

            $this->em->persist($company);
            // Non facciamo flush qui per permettere transazioni più ampie nel chiamante
        }

        return $company;
    }

    /**
     * Helper per recuperare un ruolo aziendale per codice breve.
     */
    public function getRoleByCode(string $code): ?CompanyRole
    {
        return $this->em->getRepository(CompanyRole::class)->findOneBy(['code' => $code]);
    }

    /**
     * Risolve un patrono o una banca basandosi solo sul nome (se esiste già).
     */
    public function findByCanonical(string $name, User $user): ?Company
    {
        $canonical = $this->normalizationService->normalize($name);
        return $this->companyRepository->findOneByCanonicalName($canonical, $user);
    }
}
