<?php

namespace App\Service;

use App\Entity\Asset;
use App\Entity\Campaign;
use App\Entity\Company;
use App\Entity\CompanyRole;
use App\Entity\FinancialAccount;
use App\Entity\User;
use App\Repository\CompanyRepository;
use Doctrine\ORM\EntityManagerInterface;

/**
 * Manager per la gestione dei FinancialAccount.
 * Centralizza la logica di creazione, aggiornamento e risoluzione delle banche.
 */
class FinancialAccountManager
{
    public function __construct(
        private readonly EntityManagerInterface $em,
        private readonly CompanyRepository $companyRepository
    ) {}

    /**
     * Crea un nuovo FinancialAccount per l'asset specificato.
     * Gestisce automaticamente la risoluzione della banca (esistente o nuova).
     */
    public function createForAsset(
        Asset $asset,
        User $user,
        string $credits,
        ?Company $bank,
        ?string $bankName
    ): FinancialAccount {
        $resolvedBank = $this->resolveBank($bank, $bankName, $user);

        $account = new FinancialAccount();
        $account->setUser($user);
        $account->setAsset($asset);
        $account->setCredits($credits);
        $account->setBank($resolvedBank);
        $account->setBankName(null);



        $this->em->persist($account);

        return $account;
    }

    /**
     * Aggiorna un FinancialAccount esistente o ne crea uno nuovo se non esiste.
     * Gestisce automaticamente la risoluzione della banca.
     */
    public function updateForAsset(
        Asset $asset,
        User $user,
        ?string $credits,
        ?Company $bank,
        ?string $bankName
    ): FinancialAccount {
        $account = $asset->getFinancialAccount();

        if ($account === null) {
            return $this->createForAsset(
                $asset,
                $user,
                $credits ?? '0',
                $bank,
                $bankName
            );
        }

        $resolvedBank = $this->resolveBank($bank, $bankName, $user);

        if ($credits !== null) {
            $account->setCredits($credits);
        }

        $account->setBank($resolvedBank);
        $account->setBankName(null);



        return $account;
    }

    /**
     * Risolve la Company per il FinancialAccount.
     * Se bank (Company) è selezionata, la usa ignorando bankName.
     * Se bank è null ma bankName è valorizzato:
     *   1. Cerca Company esistente con nome normalizzato (case-insensitive)
     *   2. Se non trova, crea nuova Company con ruolo BANK e isAutoGenerated=true
     */
    public function resolveBank(?Company $bank, ?string $bankName, User $user): Company
    {
        // Se bank è selezionata, usa quella
        if ($bank !== null) {
            return $bank;
        }

        $normalizedName = trim($bankName ?? '');

        // Cerca Company esistente con nome normalizzato (evita duplicati)
        $existing = $this->companyRepository->findOneByNormalizedName(
            $normalizedName,
            $user,
            CompanyRole::ROLE_BANK
        );

        if ($existing !== null) {
            return $existing;
        }

        // Crea nuova Company con ruolo BANK
        $bankRole = $this->em->getRepository(CompanyRole::class)->findOneBy([
            'code' => CompanyRole::ROLE_BANK
        ]);

        if (!$bankRole) {
            throw new \RuntimeException('CompanyRole BANK not found in database. Run context:import.');
        }

        $newBank = new Company();
        $newBank->setName($normalizedName);
        $newBank->setUser($user);
        $newBank->setCompanyRole($bankRole);
        $newBank->setIsAutoGenerated(true);
        $newBank->setContact($normalizedName . ' contact');
        $newBank->setSignLabel($normalizedName . ' sign');

        $this->em->persist($newBank);

        return $newBank;
    }
}
