<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: CompanyRepository::class)]
#[ORM\Index(name: 'idx_company_user', columns: ['user_id'])]
#[ORM\Index(name: 'idx_company_role', columns: ['company_role_id'])]
class Company
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::GUID)]
    private ?string $code = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $contact = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $signLabel = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $notes = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $sector = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $subsector = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $user = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?CompanyRole $companyRole = null;

    #[ORM\Column(options: ['default' => false])]
    private bool $isAutoGenerated = false;

    public function __construct()
    {
        $this->setCode(Uuid::v7()->toRfc4122());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getContact(): ?string
    {
        return $this->contact;
    }

    public function setContact(?string $contact): static
    {
        $this->contact = $contact;

        return $this;
    }

    public function getSignLabel(): ?string
    {
        return $this->signLabel;
    }

    public function setSignLabel(?string $signLabel): static
    {
        $this->signLabel = $signLabel;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): static
    {
        $this->notes = $notes;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getCompanyRole(): ?CompanyRole
    {
        return $this->companyRole;
    }

    public function setCompanyRole(?CompanyRole $companyRole): static
    {
        $this->companyRole = $companyRole;

        return $this;
    }

    public function getSector(): ?string
    {
        return $this->sector;
    }

    public function setSector(?string $sector): static
    {
        $this->sector = $sector;

        return $this;
    }

    public function getSubsector(): ?string
    {
        return $this->subsector;
    }

    public function setSubsector(?string $subsector): static
    {
        $this->subsector = $subsector;

        return $this;
    }

    public function isAutoGenerated(): bool
    {
        return $this->isAutoGenerated;
    }

    public function setIsAutoGenerated(bool $isAutoGenerated): static
    {
        $this->isAutoGenerated = $isAutoGenerated;

        return $this;
    }
}
