<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260106165530 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TEMPORARY TABLE __temp__campaign AS SELECT id, code, title, description, starting_year, session_day, session_year FROM campaign');
        $this->addSql('DROP TABLE campaign');
        $this->addSql('CREATE TABLE campaign (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, code BLOB NOT NULL --(DC2Type:uuid)
        , title VARCHAR(255) NOT NULL, description CLOB DEFAULT NULL, starting_year INTEGER DEFAULT NULL, session_day INTEGER DEFAULT NULL, session_year INTEGER DEFAULT NULL)');
        $this->addSql('INSERT INTO campaign (id, code, title, description, starting_year, session_day, session_year) SELECT id, code, title, description, starting_year, session_day, session_year FROM __temp__campaign');
        $this->addSql('DROP TABLE __temp__campaign');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1F1512DD77153098 ON campaign (code)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__company AS SELECT id, user_id, company_role_id, code, name, contact, sign_label, notes FROM company');
        $this->addSql('DROP TABLE company');
        $this->addSql('CREATE TABLE company (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER DEFAULT NULL, company_role_id INTEGER NOT NULL, code VARCHAR(36) NOT NULL, name VARCHAR(255) NOT NULL, contact VARCHAR(255) DEFAULT NULL, sign_label VARCHAR(255) DEFAULT NULL, notes CLOB DEFAULT NULL, CONSTRAINT FK_4FBF0947A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_4FBF0947FA9442D FOREIGN KEY (company_role_id) REFERENCES company_role (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO company (id, user_id, company_role_id, code, name, contact, sign_label, notes) SELECT id, user_id, company_role_id, code, name, contact, sign_label, notes FROM __temp__company');
        $this->addSql('DROP TABLE __temp__company');
        $this->addSql('CREATE INDEX IDX_4FBF094FA76ED395 ON company (user_id)');
        $this->addSql('CREATE INDEX IDX_4FBF094FF651387B ON company (company_role_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__cost AS SELECT id, cost_category_id, ship_id, user_id, code, title, amount, payment_day, payment_year, note, company_id, local_law_id FROM cost');
        $this->addSql('DROP TABLE cost');
        $this->addSql('CREATE TABLE cost (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, cost_category_id INTEGER NOT NULL, ship_id INTEGER NOT NULL, user_id INTEGER DEFAULT NULL, company_id INTEGER DEFAULT NULL, local_law_id INTEGER DEFAULT NULL, code VARCHAR(36) NOT NULL, title VARCHAR(255) NOT NULL, amount NUMERIC(11, 2) NOT NULL, payment_day INTEGER DEFAULT NULL, payment_year INTEGER DEFAULT NULL, note CLOB DEFAULT NULL, detail_items CLOB DEFAULT NULL --(DC2Type:json)
        , CONSTRAINT FK_182694FC31E99DA1 FOREIGN KEY (cost_category_id) REFERENCES cost_category (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_182694FCC256317D FOREIGN KEY (ship_id) REFERENCES ship (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_182694FCA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_182694FC979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_182694FC23C96FD FOREIGN KEY (local_law_id) REFERENCES local_law (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO cost (id, cost_category_id, ship_id, user_id, code, title, amount, payment_day, payment_year, note, company_id, local_law_id) SELECT id, cost_category_id, ship_id, user_id, code, title, amount, payment_day, payment_year, note, company_id, local_law_id FROM __temp__cost');
        $this->addSql('DROP TABLE __temp__cost');
        $this->addSql('CREATE INDEX IDX_182694FCA76ED395 ON cost (user_id)');
        $this->addSql('CREATE INDEX IDX_182694FCC256317D ON cost (ship_id)');
        $this->addSql('CREATE INDEX IDX_182694FC31E99DA1 ON cost (cost_category_id)');
        $this->addSql('CREATE INDEX IDX_182694FC979B1AD6 ON cost (company_id)');
        $this->addSql('CREATE INDEX IDX_182694FC23C96FD ON cost (local_law_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_charter_details AS SELECT id, income_id, area_or_route, purpose, manifest_summary, start_day, start_year, end_day, end_year, payment_terms, deposit, extras, damage_terms, cancellation_terms FROM income_charter_details');
        $this->addSql('DROP TABLE income_charter_details');
        $this->addSql('CREATE TABLE income_charter_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, area_or_route VARCHAR(255) DEFAULT NULL, purpose VARCHAR(255) DEFAULT NULL, manifest_summary CLOB DEFAULT NULL, start_day INTEGER DEFAULT NULL, start_year INTEGER DEFAULT NULL, end_day INTEGER DEFAULT NULL, end_year INTEGER DEFAULT NULL, payment_terms CLOB DEFAULT NULL, deposit NUMERIC(11, 2) DEFAULT NULL, extras CLOB DEFAULT NULL, damage_terms CLOB DEFAULT NULL, cancellation_terms CLOB DEFAULT NULL, CONSTRAINT FK_CHAR_INCOME FOREIGN KEY (income_id) REFERENCES income (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_charter_details (id, income_id, area_or_route, purpose, manifest_summary, start_day, start_year, end_day, end_year, payment_terms, deposit, extras, damage_terms, cancellation_terms) SELECT id, income_id, area_or_route, purpose, manifest_summary, start_day, start_year, end_day, end_year, payment_terms, deposit, extras, damage_terms, cancellation_terms FROM __temp__income_charter_details');
        $this->addSql('DROP TABLE __temp__income_charter_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BAAC1642640ED2C0 ON income_charter_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_contract_details AS SELECT id, income_id, job_type, location, objective, success_condition, start_day, start_year, deadline_day, deadline_year, bonus, expenses_policy, deposit, restrictions, confidentiality_level, failure_terms, cancellation_terms, payment_terms FROM income_contract_details');
        $this->addSql('DROP TABLE income_contract_details');
        $this->addSql('CREATE TABLE income_contract_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, job_type VARCHAR(255) DEFAULT NULL, location CLOB DEFAULT NULL, objective CLOB DEFAULT NULL, success_condition CLOB DEFAULT NULL, start_day INTEGER DEFAULT NULL, start_year INTEGER DEFAULT NULL, deadline_day INTEGER DEFAULT NULL, deadline_year INTEGER DEFAULT NULL, bonus NUMERIC(11, 2) DEFAULT NULL, expenses_policy CLOB DEFAULT NULL, deposit NUMERIC(11, 2) DEFAULT NULL, restrictions CLOB DEFAULT NULL, confidentiality_level CLOB DEFAULT NULL, failure_terms CLOB DEFAULT NULL, cancellation_terms CLOB DEFAULT NULL, payment_terms CLOB DEFAULT NULL, CONSTRAINT FK_CONTRACT_INCOME FOREIGN KEY (income_id) REFERENCES income (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_contract_details (id, income_id, job_type, location, objective, success_condition, start_day, start_year, deadline_day, deadline_year, bonus, expenses_policy, deposit, restrictions, confidentiality_level, failure_terms, cancellation_terms, payment_terms) SELECT id, income_id, job_type, location, objective, success_condition, start_day, start_year, deadline_day, deadline_year, bonus, expenses_policy, deposit, restrictions, confidentiality_level, failure_terms, cancellation_terms, payment_terms FROM __temp__income_contract_details');
        $this->addSql('DROP TABLE __temp__income_contract_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_69456E93640ED2C0 ON income_contract_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_freight_details AS SELECT id, income_id, origin, destination, pickup_day, pickup_year, delivery_day, delivery_year, cargo_description, cargo_qty, declared_value, payment_terms, liability_limit, cancellation_terms FROM income_freight_details');
        $this->addSql('DROP TABLE income_freight_details');
        $this->addSql('CREATE TABLE income_freight_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, origin VARCHAR(255) DEFAULT NULL, destination VARCHAR(255) DEFAULT NULL, pickup_day INTEGER DEFAULT NULL, pickup_year INTEGER DEFAULT NULL, delivery_day INTEGER DEFAULT NULL, delivery_year INTEGER DEFAULT NULL, cargo_description CLOB DEFAULT NULL, cargo_qty VARCHAR(100) DEFAULT NULL, declared_value NUMERIC(11, 2) DEFAULT NULL, payment_terms CLOB DEFAULT NULL, liability_limit NUMERIC(11, 2) DEFAULT NULL, cancellation_terms CLOB DEFAULT NULL, CONSTRAINT FK_FREIGHT_INCOME FOREIGN KEY (income_id) REFERENCES income (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_freight_details (id, income_id, origin, destination, pickup_day, pickup_year, delivery_day, delivery_year, cargo_description, cargo_qty, declared_value, payment_terms, liability_limit, cancellation_terms) SELECT id, income_id, origin, destination, pickup_day, pickup_year, delivery_day, delivery_year, cargo_description, cargo_qty, declared_value, payment_terms, liability_limit, cancellation_terms FROM __temp__income_freight_details');
        $this->addSql('DROP TABLE __temp__income_freight_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_316D3DAA640ED2C0 ON income_freight_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_insurance_details AS SELECT id, income_id, incident_ref, incident_day, incident_year, incident_location, incident_cause, loss_type, verified_loss, deductible, payment_terms, acceptance_effect, subrogation_terms, coverage_notes FROM income_insurance_details');
        $this->addSql('DROP TABLE income_insurance_details');
        $this->addSql('CREATE TABLE income_insurance_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, incident_ref VARCHAR(100) DEFAULT NULL, incident_day INTEGER DEFAULT NULL, incident_year INTEGER DEFAULT NULL, incident_location VARCHAR(255) DEFAULT NULL, incident_cause VARCHAR(255) DEFAULT NULL, loss_type VARCHAR(255) DEFAULT NULL, verified_loss NUMERIC(11, 2) DEFAULT NULL, deductible NUMERIC(11, 2) DEFAULT NULL, payment_terms CLOB DEFAULT NULL, acceptance_effect CLOB DEFAULT NULL, subrogation_terms CLOB DEFAULT NULL, coverage_notes CLOB DEFAULT NULL, CONSTRAINT FK_INSURANCE_INCOME FOREIGN KEY (income_id) REFERENCES income (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_insurance_details (id, income_id, incident_ref, incident_day, incident_year, incident_location, incident_cause, loss_type, verified_loss, deductible, payment_terms, acceptance_effect, subrogation_terms, coverage_notes) SELECT id, income_id, incident_ref, incident_day, incident_year, incident_location, incident_cause, loss_type, verified_loss, deductible, payment_terms, acceptance_effect, subrogation_terms, coverage_notes FROM __temp__income_insurance_details');
        $this->addSql('DROP TABLE __temp__income_insurance_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6EC0FE75640ED2C0 ON income_insurance_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_interest_details AS SELECT id, income_id, account_ref, instrument, principal, interest_rate, start_day, start_year, end_day, end_year, calc_method, interest_earned, net_paid, payment_terms, dispute_window FROM income_interest_details');
        $this->addSql('DROP TABLE income_interest_details');
        $this->addSql('CREATE TABLE income_interest_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, account_ref VARCHAR(100) DEFAULT NULL, instrument VARCHAR(255) DEFAULT NULL, principal NUMERIC(11, 2) DEFAULT NULL, interest_rate NUMERIC(11, 2) DEFAULT NULL, start_day INTEGER DEFAULT NULL, start_year INTEGER DEFAULT NULL, end_day INTEGER DEFAULT NULL, end_year INTEGER DEFAULT NULL, calc_method VARCHAR(100) DEFAULT NULL, interest_earned NUMERIC(11, 2) DEFAULT NULL, net_paid NUMERIC(11, 2) DEFAULT NULL, payment_terms CLOB DEFAULT NULL, dispute_window CLOB DEFAULT NULL, CONSTRAINT FK_INTEREST_INCOME FOREIGN KEY (income_id) REFERENCES income (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_interest_details (id, income_id, account_ref, instrument, principal, interest_rate, start_day, start_year, end_day, end_year, calc_method, interest_earned, net_paid, payment_terms, dispute_window) SELECT id, income_id, account_ref, instrument, principal, interest_rate, start_day, start_year, end_day, end_year, calc_method, interest_earned, net_paid, payment_terms, dispute_window FROM __temp__income_interest_details');
        $this->addSql('DROP TABLE __temp__income_interest_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6E6E6495640ED2C0 ON income_interest_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_mail_details AS SELECT id, income_id, origin, destination, dispatch_day, dispatch_year, delivery_day, delivery_year, mail_type, package_count, total_mass, security_level, seal_codes, payment_terms, proof_of_delivery, liability_limit FROM income_mail_details');
        $this->addSql('DROP TABLE income_mail_details');
        $this->addSql('CREATE TABLE income_mail_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, origin VARCHAR(255) DEFAULT NULL, destination VARCHAR(255) DEFAULT NULL, dispatch_day INTEGER DEFAULT NULL, dispatch_year INTEGER DEFAULT NULL, delivery_day INTEGER DEFAULT NULL, delivery_year INTEGER DEFAULT NULL, mail_type VARCHAR(255) DEFAULT NULL, package_count INTEGER DEFAULT NULL, total_mass NUMERIC(11, 2) DEFAULT NULL, security_level VARCHAR(255) DEFAULT NULL, seal_codes VARCHAR(255) DEFAULT NULL, payment_terms CLOB DEFAULT NULL, proof_of_delivery CLOB DEFAULT NULL, liability_limit NUMERIC(11, 2) DEFAULT NULL, CONSTRAINT FK_MAIL_INCOME FOREIGN KEY (income_id) REFERENCES income (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_mail_details (id, income_id, origin, destination, dispatch_day, dispatch_year, delivery_day, delivery_year, mail_type, package_count, total_mass, security_level, seal_codes, payment_terms, proof_of_delivery, liability_limit) SELECT id, income_id, origin, destination, dispatch_day, dispatch_year, delivery_day, delivery_year, mail_type, package_count, total_mass, security_level, seal_codes, payment_terms, proof_of_delivery, liability_limit FROM __temp__income_mail_details');
        $this->addSql('DROP TABLE __temp__income_mail_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4D0F8A05640ED2C0 ON income_mail_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_passengers_details AS SELECT id, income_id, origin, destination, departure_day, departure_year, arrival_day, arrival_year, class_or_berth, qty, passenger_names, passenger_contact, baggage_allowance, extra_baggage, payment_terms, refund_change_policy FROM income_passengers_details');
        $this->addSql('DROP TABLE income_passengers_details');
        $this->addSql('CREATE TABLE income_passengers_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, origin VARCHAR(255) DEFAULT NULL, destination VARCHAR(255) DEFAULT NULL, departure_day INTEGER DEFAULT NULL, departure_year INTEGER DEFAULT NULL, arrival_day INTEGER DEFAULT NULL, arrival_year INTEGER DEFAULT NULL, class_or_berth VARCHAR(100) DEFAULT NULL, qty INTEGER DEFAULT NULL, passenger_names CLOB DEFAULT NULL, passenger_contact VARCHAR(255) DEFAULT NULL, baggage_allowance VARCHAR(255) DEFAULT NULL, extra_baggage VARCHAR(255) DEFAULT NULL, payment_terms CLOB DEFAULT NULL, refund_change_policy CLOB DEFAULT NULL, CONSTRAINT FK_PASSENGERS_INCOME FOREIGN KEY (income_id) REFERENCES income (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_passengers_details (id, income_id, origin, destination, departure_day, departure_year, arrival_day, arrival_year, class_or_berth, qty, passenger_names, passenger_contact, baggage_allowance, extra_baggage, payment_terms, refund_change_policy) SELECT id, income_id, origin, destination, departure_day, departure_year, arrival_day, arrival_year, class_or_berth, qty, passenger_names, passenger_contact, baggage_allowance, extra_baggage, payment_terms, refund_change_policy FROM __temp__income_passengers_details');
        $this->addSql('DROP TABLE __temp__income_passengers_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E90C1830640ED2C0 ON income_passengers_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_prize_details AS SELECT id, income_id, case_ref, legal_basis, prize_description, estimated_value, disposition, payment_terms, share_split, award_trigger FROM income_prize_details');
        $this->addSql('DROP TABLE income_prize_details');
        $this->addSql('CREATE TABLE income_prize_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, case_ref VARCHAR(100) DEFAULT NULL, legal_basis CLOB DEFAULT NULL, prize_description CLOB DEFAULT NULL, estimated_value NUMERIC(11, 2) DEFAULT NULL, disposition VARCHAR(255) DEFAULT NULL, payment_terms CLOB DEFAULT NULL, share_split CLOB DEFAULT NULL, award_trigger CLOB DEFAULT NULL, CONSTRAINT FK_PRIZE_INCOME FOREIGN KEY (income_id) REFERENCES income (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_prize_details (id, income_id, case_ref, legal_basis, prize_description, estimated_value, disposition, payment_terms, share_split, award_trigger) SELECT id, income_id, case_ref, legal_basis, prize_description, estimated_value, disposition, payment_terms, share_split, award_trigger FROM __temp__income_prize_details');
        $this->addSql('DROP TABLE __temp__income_prize_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_62541F8C640ED2C0 ON income_prize_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_salvage_details AS SELECT id, income_id, case_ref, source, site_location, recovered_items_summary, qty_value, hazards, payment_terms, split_terms, rights_basis, award_trigger, dispute_process FROM income_salvage_details');
        $this->addSql('DROP TABLE income_salvage_details');
        $this->addSql('CREATE TABLE income_salvage_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, case_ref VARCHAR(100) DEFAULT NULL, source VARCHAR(100) DEFAULT NULL, site_location VARCHAR(255) DEFAULT NULL, recovered_items_summary CLOB DEFAULT NULL, qty_value NUMERIC(11, 2) DEFAULT NULL, hazards CLOB DEFAULT NULL, payment_terms CLOB DEFAULT NULL, split_terms CLOB DEFAULT NULL, rights_basis CLOB DEFAULT NULL, award_trigger CLOB DEFAULT NULL, dispute_process CLOB DEFAULT NULL, CONSTRAINT FK_SALVAGE_INCOME FOREIGN KEY (income_id) REFERENCES income (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_salvage_details (id, income_id, case_ref, source, site_location, recovered_items_summary, qty_value, hazards, payment_terms, split_terms, rights_basis, award_trigger, dispute_process) SELECT id, income_id, case_ref, source, site_location, recovered_items_summary, qty_value, hazards, payment_terms, split_terms, rights_basis, award_trigger, dispute_process FROM __temp__income_salvage_details');
        $this->addSql('DROP TABLE __temp__income_salvage_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_747BA40640ED2C0 ON income_salvage_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_services_details AS SELECT id, income_id, location, service_type, requested_by, start_day, start_year, end_day, end_year, work_summary, parts_materials, risks, payment_terms, extras, liability_limit, cancellation_terms FROM income_services_details');
        $this->addSql('DROP TABLE income_services_details');
        $this->addSql('CREATE TABLE income_services_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, location VARCHAR(255) DEFAULT NULL, service_type VARCHAR(255) DEFAULT NULL, requested_by VARCHAR(255) DEFAULT NULL, start_day INTEGER DEFAULT NULL, start_year INTEGER DEFAULT NULL, end_day INTEGER DEFAULT NULL, end_year INTEGER DEFAULT NULL, work_summary CLOB DEFAULT NULL, parts_materials CLOB DEFAULT NULL, risks CLOB DEFAULT NULL, payment_terms CLOB DEFAULT NULL, extras CLOB DEFAULT NULL, liability_limit NUMERIC(11, 2) DEFAULT NULL, cancellation_terms CLOB DEFAULT NULL, CONSTRAINT FK_SERVICES_INCOME FOREIGN KEY (income_id) REFERENCES income (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_services_details (id, income_id, location, service_type, requested_by, start_day, start_year, end_day, end_year, work_summary, parts_materials, risks, payment_terms, extras, liability_limit, cancellation_terms) SELECT id, income_id, location, service_type, requested_by, start_day, start_year, end_day, end_year, work_summary, parts_materials, risks, payment_terms, extras, liability_limit, cancellation_terms FROM __temp__income_services_details');
        $this->addSql('DROP TABLE __temp__income_services_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88EFD8AC640ED2C0 ON income_services_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_subsidy_details AS SELECT id, income_id, program_ref, origin, destination, start_day, start_year, end_day, end_year, service_level, subsidy_amount, payment_terms, milestones, reporting_requirements, non_compliance_terms, proof_requirements, cancellation_terms FROM income_subsidy_details');
        $this->addSql('DROP TABLE income_subsidy_details');
        $this->addSql('CREATE TABLE income_subsidy_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, program_ref VARCHAR(100) DEFAULT NULL, origin VARCHAR(255) DEFAULT NULL, destination VARCHAR(255) DEFAULT NULL, start_day INTEGER DEFAULT NULL, start_year INTEGER DEFAULT NULL, end_day INTEGER DEFAULT NULL, end_year INTEGER DEFAULT NULL, service_level VARCHAR(255) DEFAULT NULL, subsidy_amount NUMERIC(11, 2) DEFAULT NULL, payment_terms CLOB DEFAULT NULL, milestones CLOB DEFAULT NULL, reporting_requirements CLOB DEFAULT NULL, non_compliance_terms CLOB DEFAULT NULL, proof_requirements CLOB DEFAULT NULL, cancellation_terms CLOB DEFAULT NULL, CONSTRAINT FK_SUBSIDY_INCOME FOREIGN KEY (income_id) REFERENCES income (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_subsidy_details (id, income_id, program_ref, origin, destination, start_day, start_year, end_day, end_year, service_level, subsidy_amount, payment_terms, milestones, reporting_requirements, non_compliance_terms, proof_requirements, cancellation_terms) SELECT id, income_id, program_ref, origin, destination, start_day, start_year, end_day, end_year, service_level, subsidy_amount, payment_terms, milestones, reporting_requirements, non_compliance_terms, proof_requirements, cancellation_terms FROM __temp__income_subsidy_details');
        $this->addSql('DROP TABLE __temp__income_subsidy_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_11C99B4640ED2C0 ON income_subsidy_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_trade_details AS SELECT id, income_id, location, transfer_point, transfer_condition, goods_description, qty, grade, batch_ids, unit_price, payment_terms, delivery_method, delivery_day, delivery_year, as_is_or_warranty, warranty_text, claim_window, return_policy FROM income_trade_details');
        $this->addSql('DROP TABLE income_trade_details');
        $this->addSql('CREATE TABLE income_trade_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, location VARCHAR(255) DEFAULT NULL, transfer_point VARCHAR(255) DEFAULT NULL, transfer_condition VARCHAR(255) DEFAULT NULL, goods_description CLOB DEFAULT NULL, qty INTEGER DEFAULT NULL, grade VARCHAR(100) DEFAULT NULL, batch_ids CLOB DEFAULT NULL, unit_price NUMERIC(11, 2) DEFAULT NULL, payment_terms NUMERIC(11, 2) DEFAULT NULL, delivery_method CLOB DEFAULT NULL, delivery_day INTEGER DEFAULT NULL, delivery_year INTEGER DEFAULT NULL, as_is_or_warranty VARCHAR(255) DEFAULT NULL, warranty_text CLOB DEFAULT NULL, claim_window CLOB DEFAULT NULL, return_policy CLOB DEFAULT NULL, CONSTRAINT FK_TRADE_INCOME FOREIGN KEY (income_id) REFERENCES income (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_trade_details (id, income_id, location, transfer_point, transfer_condition, goods_description, qty, grade, batch_ids, unit_price, payment_terms, delivery_method, delivery_day, delivery_year, as_is_or_warranty, warranty_text, claim_window, return_policy) SELECT id, income_id, location, transfer_point, transfer_condition, goods_description, qty, grade, batch_ids, unit_price, payment_terms, delivery_method, delivery_day, delivery_year, as_is_or_warranty, warranty_text, claim_window, return_policy FROM __temp__income_trade_details');
        $this->addSql('DROP TABLE __temp__income_trade_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_21492504640ED2C0 ON income_trade_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__mortgage AS SELECT id, ship_id, interest_rate_id, insurance_id, user_id, code, name, start_day, start_year, ship_shares, advance_payment, discount, signed, company_id, local_law_id FROM mortgage');
        $this->addSql('DROP TABLE mortgage');
        $this->addSql('CREATE TABLE mortgage (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ship_id INTEGER NOT NULL, interest_rate_id INTEGER NOT NULL, insurance_id INTEGER DEFAULT NULL, user_id INTEGER DEFAULT NULL, company_id INTEGER DEFAULT NULL, local_law_id INTEGER DEFAULT NULL, code VARCHAR(36) NOT NULL, name VARCHAR(100) NOT NULL, start_day INTEGER NOT NULL, start_year INTEGER NOT NULL, ship_shares INTEGER DEFAULT NULL, advance_payment NUMERIC(11, 2) DEFAULT NULL, discount NUMERIC(11, 2) DEFAULT NULL, signed BOOLEAN DEFAULT 0 NOT NULL, CONSTRAINT FK_E10ABAD0C256317D FOREIGN KEY (ship_id) REFERENCES ship (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E10ABAD0B3E3E851 FOREIGN KEY (interest_rate_id) REFERENCES interest_rate (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E10ABAD0D1E63CD1 FOREIGN KEY (insurance_id) REFERENCES insurance (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E10ABAD0A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E10ABAD0979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E10ABAD023C96FD FOREIGN KEY (local_law_id) REFERENCES local_law (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO mortgage (id, ship_id, interest_rate_id, insurance_id, user_id, code, name, start_day, start_year, ship_shares, advance_payment, discount, signed, company_id, local_law_id) SELECT id, ship_id, interest_rate_id, insurance_id, user_id, code, name, start_day, start_year, ship_shares, advance_payment, discount, signed, company_id, local_law_id FROM __temp__mortgage');
        $this->addSql('DROP TABLE __temp__mortgage');
        $this->addSql('CREATE INDEX IDX_E10ABAD0A76ED395 ON mortgage (user_id)');
        $this->addSql('CREATE INDEX IDX_E10ABAD0D1E63CD1 ON mortgage (insurance_id)');
        $this->addSql('CREATE INDEX IDX_E10ABAD0B3E3E851 ON mortgage (interest_rate_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E10ABAD0C256317D ON mortgage (ship_id)');
        $this->addSql('CREATE INDEX IDX_E10ABAD0979B1AD6 ON mortgage (company_id)');
        $this->addSql('CREATE INDEX IDX_E10ABAD023C96FD ON mortgage (local_law_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__ship AS SELECT id, user_id, code, name, type, class, price, session_day, session_year, campaign_id, ship_details FROM ship');
        $this->addSql('DROP TABLE ship');
        $this->addSql('CREATE TABLE ship (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER DEFAULT NULL, campaign_id INTEGER DEFAULT NULL, code CHAR(36) NOT NULL --(DC2Type:guid)
        , name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, class VARCHAR(255) NOT NULL, price NUMERIC(11, 2) NOT NULL, session_day INTEGER DEFAULT NULL, session_year INTEGER DEFAULT NULL, ship_details CLOB DEFAULT NULL --(DC2Type:json)
        , CONSTRAINT FK_FA30EB24A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE NO ACTION ON DELETE NO ACTION NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_FA30EB24F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO ship (id, user_id, code, name, type, class, price, session_day, session_year, campaign_id, ship_details) SELECT id, user_id, code, name, type, class, price, session_day, session_year, campaign_id, ship_details FROM __temp__ship');
        $this->addSql('DROP TABLE __temp__ship');
        $this->addSql('CREATE INDEX IDX_FA30EB24A76ED395 ON ship (user_id)');
        $this->addSql('CREATE INDEX IDX_FA30EB24F639F774 ON ship (campaign_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TEMPORARY TABLE __temp__campaign AS SELECT id, title, code, description, starting_year, session_day, session_year FROM campaign');
        $this->addSql('DROP TABLE campaign');
        $this->addSql('CREATE TABLE campaign (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, title VARCHAR(255) NOT NULL, code VARCHAR(36) NOT NULL, description CLOB DEFAULT NULL, starting_year INTEGER DEFAULT NULL, session_day INTEGER DEFAULT NULL, session_year INTEGER DEFAULT NULL)');
        $this->addSql('INSERT INTO campaign (id, title, code, description, starting_year, session_day, session_year) SELECT id, title, code, description, starting_year, session_day, session_year FROM __temp__campaign');
        $this->addSql('DROP TABLE __temp__campaign');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F639F77477153098 ON campaign (code)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__company AS SELECT id, user_id, company_role_id, code, name, contact, sign_label, notes FROM company');
        $this->addSql('DROP TABLE company');
        $this->addSql('CREATE TABLE company (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER DEFAULT NULL, company_role_id INTEGER NOT NULL, code VARCHAR(36) NOT NULL, name VARCHAR(255) NOT NULL, contact VARCHAR(255) DEFAULT NULL, sign_label VARCHAR(255) DEFAULT NULL, notes CLOB DEFAULT NULL, CONSTRAINT FK_4FBF094FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_4FBF094FF651387B FOREIGN KEY (company_role_id) REFERENCES company_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO company (id, user_id, company_role_id, code, name, contact, sign_label, notes) SELECT id, user_id, company_role_id, code, name, contact, sign_label, notes FROM __temp__company');
        $this->addSql('DROP TABLE __temp__company');
        $this->addSql('CREATE INDEX IDX_4FBF0947FA9442D ON company (company_role_id)');
        $this->addSql('CREATE INDEX IDX_4FBF0947A76ED395 ON company (user_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__cost AS SELECT id, cost_category_id, ship_id, user_id, company_id, local_law_id, code, title, amount, payment_day, payment_year, note FROM cost');
        $this->addSql('DROP TABLE cost');
        $this->addSql('CREATE TABLE cost (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, cost_category_id INTEGER NOT NULL, ship_id INTEGER NOT NULL, user_id INTEGER DEFAULT NULL, company_id INTEGER DEFAULT NULL, local_law_id INTEGER DEFAULT NULL, code VARCHAR(36) NOT NULL, title VARCHAR(255) NOT NULL, amount NUMERIC(11, 2) NOT NULL, payment_day INTEGER DEFAULT NULL, payment_year INTEGER DEFAULT NULL, note CLOB DEFAULT NULL, CONSTRAINT FK_182694FC31E99DA1 FOREIGN KEY (cost_category_id) REFERENCES cost_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_182694FCC256317D FOREIGN KEY (ship_id) REFERENCES ship (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_182694FCA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO cost (id, cost_category_id, ship_id, user_id, company_id, local_law_id, code, title, amount, payment_day, payment_year, note) SELECT id, cost_category_id, ship_id, user_id, company_id, local_law_id, code, title, amount, payment_day, payment_year, note FROM __temp__cost');
        $this->addSql('DROP TABLE __temp__cost');
        $this->addSql('CREATE INDEX IDX_182694FC31E99DA1 ON cost (cost_category_id)');
        $this->addSql('CREATE INDEX IDX_182694FCC256317D ON cost (ship_id)');
        $this->addSql('CREATE INDEX IDX_182694FCA76ED395 ON cost (user_id)');
        $this->addSql('CREATE INDEX IDX_COST_LOCAL_LAW_ID ON cost (local_law_id)');
        $this->addSql('CREATE INDEX IDX_3C2AA97979B1AD6 ON cost (company_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_charter_details AS SELECT id, income_id, area_or_route, purpose, manifest_summary, start_day, start_year, end_day, end_year, payment_terms, deposit, extras, damage_terms, cancellation_terms FROM income_charter_details');
        $this->addSql('DROP TABLE income_charter_details');
        $this->addSql('CREATE TABLE income_charter_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, area_or_route VARCHAR(255) DEFAULT NULL, purpose VARCHAR(255) DEFAULT NULL, manifest_summary CLOB DEFAULT NULL, start_day INTEGER DEFAULT NULL, start_year INTEGER DEFAULT NULL, end_day INTEGER DEFAULT NULL, end_year INTEGER DEFAULT NULL, payment_terms CLOB DEFAULT NULL, deposit NUMERIC(11, 2) DEFAULT NULL, extras CLOB DEFAULT NULL, damage_terms CLOB DEFAULT NULL, cancellation_terms CLOB DEFAULT NULL, CONSTRAINT FK_BAAC1642640ED2C0 FOREIGN KEY (income_id) REFERENCES income (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_charter_details (id, income_id, area_or_route, purpose, manifest_summary, start_day, start_year, end_day, end_year, payment_terms, deposit, extras, damage_terms, cancellation_terms) SELECT id, income_id, area_or_route, purpose, manifest_summary, start_day, start_year, end_day, end_year, payment_terms, deposit, extras, damage_terms, cancellation_terms FROM __temp__income_charter_details');
        $this->addSql('DROP TABLE __temp__income_charter_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INCOME_CHARTER_DETAILS_INCOME ON income_charter_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_contract_details AS SELECT id, income_id, job_type, location, objective, success_condition, start_day, start_year, deadline_day, deadline_year, bonus, expenses_policy, deposit, restrictions, confidentiality_level, failure_terms, cancellation_terms, payment_terms FROM income_contract_details');
        $this->addSql('DROP TABLE income_contract_details');
        $this->addSql('CREATE TABLE income_contract_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, job_type VARCHAR(255) DEFAULT NULL, location CLOB DEFAULT NULL, objective CLOB DEFAULT NULL, success_condition CLOB DEFAULT NULL, start_day INTEGER DEFAULT NULL, start_year INTEGER DEFAULT NULL, deadline_day INTEGER DEFAULT NULL, deadline_year INTEGER DEFAULT NULL, bonus NUMERIC(11, 2) DEFAULT NULL, expenses_policy CLOB DEFAULT NULL, deposit NUMERIC(11, 2) DEFAULT NULL, restrictions CLOB DEFAULT NULL, confidentiality_level CLOB DEFAULT NULL, failure_terms CLOB DEFAULT NULL, cancellation_terms CLOB DEFAULT NULL, payment_terms CLOB DEFAULT NULL, CONSTRAINT FK_69456E93640ED2C0 FOREIGN KEY (income_id) REFERENCES income (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_contract_details (id, income_id, job_type, location, objective, success_condition, start_day, start_year, deadline_day, deadline_year, bonus, expenses_policy, deposit, restrictions, confidentiality_level, failure_terms, cancellation_terms, payment_terms) SELECT id, income_id, job_type, location, objective, success_condition, start_day, start_year, deadline_day, deadline_year, bonus, expenses_policy, deposit, restrictions, confidentiality_level, failure_terms, cancellation_terms, payment_terms FROM __temp__income_contract_details');
        $this->addSql('DROP TABLE __temp__income_contract_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INCOME_CONTRACT_DETAILS_INCOME ON income_contract_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_freight_details AS SELECT id, income_id, origin, destination, pickup_day, pickup_year, delivery_day, delivery_year, cargo_description, cargo_qty, declared_value, payment_terms, liability_limit, cancellation_terms FROM income_freight_details');
        $this->addSql('DROP TABLE income_freight_details');
        $this->addSql('CREATE TABLE income_freight_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, origin VARCHAR(255) DEFAULT NULL, destination VARCHAR(255) DEFAULT NULL, pickup_day INTEGER DEFAULT NULL, pickup_year INTEGER DEFAULT NULL, delivery_day INTEGER DEFAULT NULL, delivery_year INTEGER DEFAULT NULL, cargo_description CLOB DEFAULT NULL, cargo_qty VARCHAR(100) DEFAULT NULL, declared_value NUMERIC(11, 2) DEFAULT NULL, payment_terms CLOB DEFAULT NULL, liability_limit NUMERIC(11, 2) DEFAULT NULL, cancellation_terms CLOB DEFAULT NULL, CONSTRAINT FK_316D3DAA640ED2C0 FOREIGN KEY (income_id) REFERENCES income (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_freight_details (id, income_id, origin, destination, pickup_day, pickup_year, delivery_day, delivery_year, cargo_description, cargo_qty, declared_value, payment_terms, liability_limit, cancellation_terms) SELECT id, income_id, origin, destination, pickup_day, pickup_year, delivery_day, delivery_year, cargo_description, cargo_qty, declared_value, payment_terms, liability_limit, cancellation_terms FROM __temp__income_freight_details');
        $this->addSql('DROP TABLE __temp__income_freight_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INCOME_FREIGHT_DETAILS_INCOME ON income_freight_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_insurance_details AS SELECT id, income_id, incident_ref, incident_day, incident_year, incident_location, incident_cause, loss_type, verified_loss, deductible, payment_terms, acceptance_effect, subrogation_terms, coverage_notes FROM income_insurance_details');
        $this->addSql('DROP TABLE income_insurance_details');
        $this->addSql('CREATE TABLE income_insurance_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, incident_ref VARCHAR(100) DEFAULT NULL, incident_day INTEGER DEFAULT NULL, incident_year INTEGER DEFAULT NULL, incident_location VARCHAR(255) DEFAULT NULL, incident_cause VARCHAR(255) DEFAULT NULL, loss_type VARCHAR(255) DEFAULT NULL, verified_loss NUMERIC(11, 2) DEFAULT NULL, deductible NUMERIC(11, 2) DEFAULT NULL, payment_terms CLOB DEFAULT NULL, acceptance_effect CLOB DEFAULT NULL, subrogation_terms CLOB DEFAULT NULL, coverage_notes CLOB DEFAULT NULL, CONSTRAINT FK_6EC0FE75640ED2C0 FOREIGN KEY (income_id) REFERENCES income (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_insurance_details (id, income_id, incident_ref, incident_day, incident_year, incident_location, incident_cause, loss_type, verified_loss, deductible, payment_terms, acceptance_effect, subrogation_terms, coverage_notes) SELECT id, income_id, incident_ref, incident_day, incident_year, incident_location, incident_cause, loss_type, verified_loss, deductible, payment_terms, acceptance_effect, subrogation_terms, coverage_notes FROM __temp__income_insurance_details');
        $this->addSql('DROP TABLE __temp__income_insurance_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INSURANCE_INCOME ON income_insurance_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_interest_details AS SELECT id, income_id, account_ref, instrument, principal, interest_rate, start_day, start_year, end_day, end_year, calc_method, interest_earned, net_paid, payment_terms, dispute_window FROM income_interest_details');
        $this->addSql('DROP TABLE income_interest_details');
        $this->addSql('CREATE TABLE income_interest_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, account_ref VARCHAR(100) DEFAULT NULL, instrument VARCHAR(255) DEFAULT NULL, principal NUMERIC(11, 2) DEFAULT NULL, interest_rate NUMERIC(11, 2) DEFAULT NULL, start_day INTEGER DEFAULT NULL, start_year INTEGER DEFAULT NULL, end_day INTEGER DEFAULT NULL, end_year INTEGER DEFAULT NULL, calc_method VARCHAR(100) DEFAULT NULL, interest_earned NUMERIC(11, 2) DEFAULT NULL, net_paid NUMERIC(11, 2) DEFAULT NULL, payment_terms CLOB DEFAULT NULL, dispute_window CLOB DEFAULT NULL, CONSTRAINT FK_6E6E6495640ED2C0 FOREIGN KEY (income_id) REFERENCES income (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_interest_details (id, income_id, account_ref, instrument, principal, interest_rate, start_day, start_year, end_day, end_year, calc_method, interest_earned, net_paid, payment_terms, dispute_window) SELECT id, income_id, account_ref, instrument, principal, interest_rate, start_day, start_year, end_day, end_year, calc_method, interest_earned, net_paid, payment_terms, dispute_window FROM __temp__income_interest_details');
        $this->addSql('DROP TABLE __temp__income_interest_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INTEREST_INCOME ON income_interest_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_mail_details AS SELECT id, income_id, origin, destination, dispatch_day, dispatch_year, delivery_day, delivery_year, mail_type, package_count, total_mass, security_level, seal_codes, payment_terms, proof_of_delivery, liability_limit FROM income_mail_details');
        $this->addSql('DROP TABLE income_mail_details');
        $this->addSql('CREATE TABLE income_mail_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, origin VARCHAR(255) DEFAULT NULL, destination VARCHAR(255) DEFAULT NULL, dispatch_day INTEGER DEFAULT NULL, dispatch_year INTEGER DEFAULT NULL, delivery_day INTEGER DEFAULT NULL, delivery_year INTEGER DEFAULT NULL, mail_type VARCHAR(255) DEFAULT NULL, package_count INTEGER DEFAULT NULL, total_mass NUMERIC(11, 2) DEFAULT NULL, security_level VARCHAR(255) DEFAULT NULL, seal_codes VARCHAR(255) DEFAULT NULL, payment_terms CLOB DEFAULT NULL, proof_of_delivery CLOB DEFAULT NULL, liability_limit NUMERIC(11, 2) DEFAULT NULL, CONSTRAINT FK_4D0F8A05640ED2C0 FOREIGN KEY (income_id) REFERENCES income (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_mail_details (id, income_id, origin, destination, dispatch_day, dispatch_year, delivery_day, delivery_year, mail_type, package_count, total_mass, security_level, seal_codes, payment_terms, proof_of_delivery, liability_limit) SELECT id, income_id, origin, destination, dispatch_day, dispatch_year, delivery_day, delivery_year, mail_type, package_count, total_mass, security_level, seal_codes, payment_terms, proof_of_delivery, liability_limit FROM __temp__income_mail_details');
        $this->addSql('DROP TABLE __temp__income_mail_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INCOME_MAIL_DETAILS_INCOME ON income_mail_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_passengers_details AS SELECT id, income_id, origin, destination, departure_day, departure_year, arrival_day, arrival_year, class_or_berth, qty, passenger_names, passenger_contact, baggage_allowance, extra_baggage, payment_terms, refund_change_policy FROM income_passengers_details');
        $this->addSql('DROP TABLE income_passengers_details');
        $this->addSql('CREATE TABLE income_passengers_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, origin VARCHAR(255) DEFAULT NULL, destination VARCHAR(255) DEFAULT NULL, departure_day INTEGER DEFAULT NULL, departure_year INTEGER DEFAULT NULL, arrival_day INTEGER DEFAULT NULL, arrival_year INTEGER DEFAULT NULL, class_or_berth VARCHAR(100) DEFAULT NULL, qty INTEGER DEFAULT NULL, passenger_names CLOB DEFAULT NULL, passenger_contact VARCHAR(255) DEFAULT NULL, baggage_allowance VARCHAR(255) DEFAULT NULL, extra_baggage VARCHAR(255) DEFAULT NULL, payment_terms CLOB DEFAULT NULL, refund_change_policy CLOB DEFAULT NULL, CONSTRAINT FK_E90C1830640ED2C0 FOREIGN KEY (income_id) REFERENCES income (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_passengers_details (id, income_id, origin, destination, departure_day, departure_year, arrival_day, arrival_year, class_or_berth, qty, passenger_names, passenger_contact, baggage_allowance, extra_baggage, payment_terms, refund_change_policy) SELECT id, income_id, origin, destination, departure_day, departure_year, arrival_day, arrival_year, class_or_berth, qty, passenger_names, passenger_contact, baggage_allowance, extra_baggage, payment_terms, refund_change_policy FROM __temp__income_passengers_details');
        $this->addSql('DROP TABLE __temp__income_passengers_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INCOME_PASSENGERS_DETAILS_INCOME ON income_passengers_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_prize_details AS SELECT id, income_id, case_ref, legal_basis, prize_description, estimated_value, disposition, payment_terms, share_split, award_trigger FROM income_prize_details');
        $this->addSql('DROP TABLE income_prize_details');
        $this->addSql('CREATE TABLE income_prize_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, case_ref VARCHAR(100) DEFAULT NULL, legal_basis CLOB DEFAULT NULL, prize_description CLOB DEFAULT NULL, estimated_value NUMERIC(11, 2) DEFAULT NULL, disposition VARCHAR(255) DEFAULT NULL, payment_terms CLOB DEFAULT NULL, share_split CLOB DEFAULT NULL, award_trigger CLOB DEFAULT NULL, CONSTRAINT FK_62541F8C640ED2C0 FOREIGN KEY (income_id) REFERENCES income (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_prize_details (id, income_id, case_ref, legal_basis, prize_description, estimated_value, disposition, payment_terms, share_split, award_trigger) SELECT id, income_id, case_ref, legal_basis, prize_description, estimated_value, disposition, payment_terms, share_split, award_trigger FROM __temp__income_prize_details');
        $this->addSql('DROP TABLE __temp__income_prize_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PRIZE_INCOME ON income_prize_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_salvage_details AS SELECT id, income_id, case_ref, source, site_location, recovered_items_summary, qty_value, hazards, payment_terms, split_terms, rights_basis, award_trigger, dispute_process FROM income_salvage_details');
        $this->addSql('DROP TABLE income_salvage_details');
        $this->addSql('CREATE TABLE income_salvage_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, case_ref VARCHAR(100) DEFAULT NULL, source VARCHAR(100) DEFAULT NULL, site_location VARCHAR(255) DEFAULT NULL, recovered_items_summary CLOB DEFAULT NULL, qty_value NUMERIC(11, 2) DEFAULT NULL, hazards CLOB DEFAULT NULL, payment_terms CLOB DEFAULT NULL, split_terms CLOB DEFAULT NULL, rights_basis CLOB DEFAULT NULL, award_trigger CLOB DEFAULT NULL, dispute_process CLOB DEFAULT NULL, CONSTRAINT FK_747BA40640ED2C0 FOREIGN KEY (income_id) REFERENCES income (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_salvage_details (id, income_id, case_ref, source, site_location, recovered_items_summary, qty_value, hazards, payment_terms, split_terms, rights_basis, award_trigger, dispute_process) SELECT id, income_id, case_ref, source, site_location, recovered_items_summary, qty_value, hazards, payment_terms, split_terms, rights_basis, award_trigger, dispute_process FROM __temp__income_salvage_details');
        $this->addSql('DROP TABLE __temp__income_salvage_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SALVAGE_INCOME ON income_salvage_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_services_details AS SELECT id, income_id, location, service_type, requested_by, start_day, start_year, end_day, end_year, work_summary, parts_materials, risks, payment_terms, extras, liability_limit, cancellation_terms FROM income_services_details');
        $this->addSql('DROP TABLE income_services_details');
        $this->addSql('CREATE TABLE income_services_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, location VARCHAR(255) DEFAULT NULL, service_type VARCHAR(255) DEFAULT NULL, requested_by VARCHAR(255) DEFAULT NULL, start_day INTEGER DEFAULT NULL, start_year INTEGER DEFAULT NULL, end_day INTEGER DEFAULT NULL, end_year INTEGER DEFAULT NULL, work_summary CLOB DEFAULT NULL, parts_materials CLOB DEFAULT NULL, risks CLOB DEFAULT NULL, payment_terms CLOB DEFAULT NULL, extras CLOB DEFAULT NULL, liability_limit NUMERIC(11, 2) DEFAULT NULL, cancellation_terms CLOB DEFAULT NULL, CONSTRAINT FK_88EFD8AC640ED2C0 FOREIGN KEY (income_id) REFERENCES income (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_services_details (id, income_id, location, service_type, requested_by, start_day, start_year, end_day, end_year, work_summary, parts_materials, risks, payment_terms, extras, liability_limit, cancellation_terms) SELECT id, income_id, location, service_type, requested_by, start_day, start_year, end_day, end_year, work_summary, parts_materials, risks, payment_terms, extras, liability_limit, cancellation_terms FROM __temp__income_services_details');
        $this->addSql('DROP TABLE __temp__income_services_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_SERVICES_INCOME ON income_services_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_subsidy_details AS SELECT id, income_id, program_ref, origin, destination, start_day, start_year, end_day, end_year, service_level, subsidy_amount, payment_terms, milestones, reporting_requirements, non_compliance_terms, proof_requirements, cancellation_terms FROM income_subsidy_details');
        $this->addSql('DROP TABLE income_subsidy_details');
        $this->addSql('CREATE TABLE income_subsidy_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, program_ref VARCHAR(100) DEFAULT NULL, origin VARCHAR(255) DEFAULT NULL, destination VARCHAR(255) DEFAULT NULL, start_day INTEGER DEFAULT NULL, start_year INTEGER DEFAULT NULL, end_day INTEGER DEFAULT NULL, end_year INTEGER DEFAULT NULL, service_level VARCHAR(255) DEFAULT NULL, subsidy_amount NUMERIC(11, 2) DEFAULT NULL, payment_terms CLOB DEFAULT NULL, milestones CLOB DEFAULT NULL, reporting_requirements CLOB DEFAULT NULL, non_compliance_terms CLOB DEFAULT NULL, proof_requirements CLOB DEFAULT NULL, cancellation_terms CLOB DEFAULT NULL, CONSTRAINT FK_11C99B4640ED2C0 FOREIGN KEY (income_id) REFERENCES income (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_subsidy_details (id, income_id, program_ref, origin, destination, start_day, start_year, end_day, end_year, service_level, subsidy_amount, payment_terms, milestones, reporting_requirements, non_compliance_terms, proof_requirements, cancellation_terms) SELECT id, income_id, program_ref, origin, destination, start_day, start_year, end_day, end_year, service_level, subsidy_amount, payment_terms, milestones, reporting_requirements, non_compliance_terms, proof_requirements, cancellation_terms FROM __temp__income_subsidy_details');
        $this->addSql('DROP TABLE __temp__income_subsidy_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INCOME_SUBSIDY_DETAILS_INCOME ON income_subsidy_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__income_trade_details AS SELECT id, income_id, location, transfer_point, transfer_condition, goods_description, qty, grade, batch_ids, unit_price, payment_terms, delivery_method, delivery_day, delivery_year, as_is_or_warranty, warranty_text, claim_window, return_policy FROM income_trade_details');
        $this->addSql('DROP TABLE income_trade_details');
        $this->addSql('CREATE TABLE income_trade_details (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, income_id INTEGER NOT NULL, location VARCHAR(255) DEFAULT NULL, transfer_point VARCHAR(255) DEFAULT NULL, transfer_condition VARCHAR(255) DEFAULT NULL, goods_description CLOB DEFAULT NULL, qty INTEGER DEFAULT NULL, grade VARCHAR(100) DEFAULT NULL, batch_ids CLOB DEFAULT NULL, unit_price NUMERIC(11, 2) DEFAULT NULL, payment_terms NUMERIC(11, 2) DEFAULT NULL, delivery_method CLOB DEFAULT NULL, delivery_day INTEGER DEFAULT NULL, delivery_year INTEGER DEFAULT NULL, as_is_or_warranty VARCHAR(255) DEFAULT NULL, warranty_text CLOB DEFAULT NULL, claim_window CLOB DEFAULT NULL, return_policy CLOB DEFAULT NULL, CONSTRAINT FK_21492504640ED2C0 FOREIGN KEY (income_id) REFERENCES income (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO income_trade_details (id, income_id, location, transfer_point, transfer_condition, goods_description, qty, grade, batch_ids, unit_price, payment_terms, delivery_method, delivery_day, delivery_year, as_is_or_warranty, warranty_text, claim_window, return_policy) SELECT id, income_id, location, transfer_point, transfer_condition, goods_description, qty, grade, batch_ids, unit_price, payment_terms, delivery_method, delivery_day, delivery_year, as_is_or_warranty, warranty_text, claim_window, return_policy FROM __temp__income_trade_details');
        $this->addSql('DROP TABLE __temp__income_trade_details');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_INCOME_TRADE_DETAILS_INCOME ON income_trade_details (income_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__mortgage AS SELECT id, ship_id, interest_rate_id, insurance_id, user_id, company_id, local_law_id, code, name, start_day, start_year, ship_shares, advance_payment, discount, signed FROM mortgage');
        $this->addSql('DROP TABLE mortgage');
        $this->addSql('CREATE TABLE mortgage (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, ship_id INTEGER NOT NULL, interest_rate_id INTEGER NOT NULL, insurance_id INTEGER DEFAULT NULL, user_id INTEGER DEFAULT NULL, company_id INTEGER DEFAULT NULL, local_law_id INTEGER DEFAULT NULL, code VARCHAR(36) NOT NULL, name VARCHAR(100) NOT NULL, start_day INTEGER NOT NULL, start_year INTEGER NOT NULL, ship_shares INTEGER DEFAULT NULL, advance_payment NUMERIC(11, 2) DEFAULT NULL, discount NUMERIC(11, 2) DEFAULT NULL, signed BOOLEAN DEFAULT 0 NOT NULL, CONSTRAINT FK_E10ABAD0C256317D FOREIGN KEY (ship_id) REFERENCES ship (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E10ABAD0B3E3E851 FOREIGN KEY (interest_rate_id) REFERENCES interest_rate (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E10ABAD0D1E63CD1 FOREIGN KEY (insurance_id) REFERENCES insurance (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E10ABAD0A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO mortgage (id, ship_id, interest_rate_id, insurance_id, user_id, company_id, local_law_id, code, name, start_day, start_year, ship_shares, advance_payment, discount, signed) SELECT id, ship_id, interest_rate_id, insurance_id, user_id, company_id, local_law_id, code, name, start_day, start_year, ship_shares, advance_payment, discount, signed FROM __temp__mortgage');
        $this->addSql('DROP TABLE __temp__mortgage');
        $this->addSql('CREATE INDEX IDX_E10ABAD0B3E3E851 ON mortgage (interest_rate_id)');
        $this->addSql('CREATE INDEX IDX_E10ABAD0D1E63CD1 ON mortgage (insurance_id)');
        $this->addSql('CREATE INDEX IDX_E10ABAD0A76ED395 ON mortgage (user_id)');
        $this->addSql('CREATE INDEX IDX_E10ABAD0C256317D ON mortgage (ship_id)');
        $this->addSql('CREATE INDEX IDX_MORTGAGE_LOCAL_LAW_ID ON mortgage (local_law_id)');
        $this->addSql('CREATE INDEX IDX_MORTGAGE_COMPANY_ID ON mortgage (company_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_MORTGAGE_SHIP_ID ON mortgage (ship_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__ship AS SELECT id, user_id, campaign_id, code, name, type, class, price, session_day, session_year, ship_details FROM ship');
        $this->addSql('DROP TABLE ship');
        $this->addSql('CREATE TABLE ship (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER DEFAULT NULL, campaign_id INTEGER DEFAULT NULL, code CHAR(36) NOT NULL --(DC2Type:guid)
        , name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, class VARCHAR(255) NOT NULL, price NUMERIC(11, 2) NOT NULL, session_day INTEGER DEFAULT NULL, session_year INTEGER DEFAULT NULL, ship_details CLOB DEFAULT NULL, CONSTRAINT FK_FA30EB24A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO ship (id, user_id, campaign_id, code, name, type, class, price, session_day, session_year, ship_details) SELECT id, user_id, campaign_id, code, name, type, class, price, session_day, session_year, ship_details FROM __temp__ship');
        $this->addSql('DROP TABLE __temp__ship');
        $this->addSql('CREATE INDEX IDX_FA30EB24A76ED395 ON ship (user_id)');
        $this->addSql('CREATE INDEX IDX_EF4E8F97F639F774 ON ship (campaign_id)');
    }
}
