<?php

namespace App\Controller;

use App\Entity\Cost;
use App\Entity\Campaign;
use App\Entity\Asset;
use App\Entity\CostCategory;
use App\Form\CostType;
use App\Security\Voter\CostVoter;
use App\Service\ListViewHelper;
use App\Service\Pdf\PdfGeneratorInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\Income;

final class CostController extends BaseController
{
    public const CONTROLLER_NAME = 'CostController';

    public function __construct(
        private readonly \App\Service\FinancialAccountManager $accountManager
    ) {}

    #[Route('/cost/index', name: 'app_cost_index', methods: ['GET'])]
    public function index(Request $request, EntityManagerInterface $em, ListViewHelper $listViewHelper): Response
    {
        $user = $this->getUser();
        $filters = $listViewHelper->collectFilters($request, [
            'title',
            'category' => ['type' => 'int'],
            'asset' => ['type' => 'int'],
            'campaign' => ['type' => 'int'],
        ]);
        $page = $listViewHelper->getPage($request);
        $perPage = 10;

        $costs = [];
        $total = 0;
        $categories = [];
        $assets = [];
        $campaigns = [];

        if ($user instanceof \App\Entity\User) {
            $result = $em->getRepository(Cost::class)->findForUserWithFilters($user, $filters, $page, $perPage);
            $costs = $result['items'];
            $total = $result['total'];

            $totalPages = max(1, (int) ceil($total / $perPage));
            $clampedPage = $listViewHelper->clampPage($page, $totalPages);
            if ($clampedPage !== $page) {
                $page = $clampedPage;
                $result = $em->getRepository(Cost::class)->findForUserWithFilters($user, $filters, $page, $perPage);
                $costs = $result['items'];
            }

            $categories = $em->getRepository(CostCategory::class)->findBy([], ['code' => 'ASC']);
            $assets = $em->getRepository(Asset::class)->findAllForUser($user);
            $campaigns = $em->getRepository(Campaign::class)->findAllForUser($user);
        }

        $pagination = $listViewHelper->buildPaginationPayload($page, $perPage, $total);

        return $this->render('cost/index.html.twig', [
            'controller_name' => self::CONTROLLER_NAME,
            'costs' => $costs,
            'filters' => $filters,
            'categories' => $categories,
            'assets' => $assets,
            'campaigns' => $campaigns,
            'pagination' => $pagination,
        ]);
    }

    #[Route('/cost/new', name: 'app_cost_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $em): Response
    {
        $user = $this->getUser();
        if (!$user instanceof \App\Entity\User) {
            throw $this->createAccessDeniedException();
        }

        $cost = new Cost();
        $faId = $request->query->get('financialAccount');
        if ($faId) {
            $fa = $em->getRepository(\App\Entity\FinancialAccount::class)->find($faId);
            if ($fa && $fa->getUser() === $user) {
                $cost->setFinancialAccount($fa);
            }
        }

        $form = $this->createForm(CostType::class, $cost, ['user' => $user]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            // 1. DEBIT ACCOUNT (Source / My Account)
            $financialAccount = $form->get('financialAccount')->getData();
            $asset = $form->get('asset')->getData(); // Mapped false

            if (!$financialAccount) {
                $bank = $form->get('bank')->getData();
                $bankName = $form->get('bankName')->getData();

                if (($bank || $bankName) && $asset) {
                    $financialAccount = $this->accountManager->updateForAsset(
                        $asset,
                        $user,
                        null,
                        $bank,
                        $bankName
                    );
                }
            }

            if ($financialAccount) {
                $cost->setFinancialAccount($financialAccount);
            }

            // 2. CREDIT ENTITY (Vendor)
            $vendorCompany = $form->get('company')->getData();
            if (!$vendorCompany) {
                $vendorName = $form->get('vendorName')->getData();
                $vendorRole = $form->get('vendorRole')->getData();

                if ($vendorName && $vendorRole) {
                    $newCompany = new \App\Entity\Company();
                    $newCompany->setName($vendorName);
                    $newCompany->setCompanyRole($vendorRole);
                    $newCompany->setUser($user);
                    $newCompany->setIsAutoGenerated(true);
                    $newCompany->setContact($vendorName . ' contact');
                    $newCompany->setSignLabel($vendorName);

                    $em->persist($newCompany);
                    $cost->setCompany($newCompany);
                }
            }

            $em->persist($cost);
            $em->flush();

            return $this->redirectToRoute('app_cost_index');
        }

        return $this->renderTurbo('cost/edit.html.twig', [
            'controller_name' => self::CONTROLLER_NAME,
            'cost' => $cost,
            'form' => $form,
        ]);
    }

    #[Route('/cost/edit/{id}', name: 'app_cost_edit', methods: ['GET', 'POST'])]
    public function edit(
        int $id,
        Request $request,
        EntityManagerInterface $em
    ): Response {
        $user = $this->getUser();
        if (!$user instanceof \App\Entity\User) {
            throw $this->createAccessDeniedException();
        }

        $cost = $em->getRepository(Cost::class)->findOneForUser($id, $user);
        if (!$cost) {
            throw new NotFoundHttpException();
        }

        $form = $this->createForm(CostType::class, $cost, ['user' => $user]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // 1. DEBIT ACCOUNT (Source)
            $financialAccount = $form->get('financialAccount')->getData();
            $asset = $form->get('asset')->getData();

            if (!$financialAccount) {
                $bank = $form->get('bank')->getData();
                $bankName = $form->get('bankName')->getData();

                if (($bank || $bankName) && $asset) {
                    $financialAccount = $this->accountManager->updateForAsset(
                        $asset,
                        $user,
                        null,
                        $bank,
                        $bankName
                    );
                }
            }

            if ($financialAccount) {
                $cost->setFinancialAccount($financialAccount);
            }

            // 2. CREDIT ENTITY (Vendor) -> Usually defined, but if changing...
            $vendorCompany = $form->get('company')->getData();
            if (!$vendorCompany) {
                $vendorName = $form->get('vendorName')->getData();
                $vendorRole = $form->get('vendorRole')->getData();

                if ($vendorName && $vendorRole) {
                    $newCompany = new \App\Entity\Company();
                    $newCompany->setName($vendorName);
                    $newCompany->setCompanyRole($vendorRole);
                    $newCompany->setUser($user);
                    $newCompany->setIsAutoGenerated(true);
                    $newCompany->setContact($vendorName . ' contact');
                    $newCompany->setSignLabel($vendorName);

                    $em->persist($newCompany);
                    $cost->setCompany($newCompany);
                }
            }

            $em->flush();
            $this->addFlash('warning', 'LEDGER INTEGRITY EVENT. Correction appended. Original error archived for forensic audit.');

            return $this->redirectToRoute('app_cost_index');
        }

        return $this->renderTurbo('cost/edit.html.twig', [
            'controller_name' => self::CONTROLLER_NAME,

            'cost' => $cost,
            'form' => $form,
            'asset' => $cost->getFinancialAccount()?->getAsset(),
        ]);
    }

    #[Route('/cost/delete/{id}', name: 'app_cost_delete', methods: ['GET', 'POST'])]
    public function delete(
        int $id,
        EntityManagerInterface $em
    ): Response {
        $user = $this->getUser();
        if (!$user instanceof \App\Entity\User) {
            throw $this->createAccessDeniedException();
        }

        $cost = $em->getRepository(Cost::class)->findOneForUser($id, $user);
        if (!$cost) {
            throw new NotFoundHttpException();
        }

        $this->denyAccessUnlessGranted(CostVoter::DELETE, $cost);

        // integrity check: is this cost sold?
        $sale = $em->getRepository(\App\Entity\Income::class)->findOneBy(['purchaseCost' => $cost]);
        if ($sale) {
            $this->addFlash('error', 'Cannot delete this Item: it is linked to a Sale Transaction (' . $sale->getTitle() . '). Refund/Delete the Sale first.');
            return $this->redirectToRoute('app_cost_index');
        }

        $em->remove($cost);
        $em->flush();

        return $this->redirectToRoute('app_cost_index');
    }

    #[Route('/cost/{id}/pdf', name: 'app_cost_pdf', methods: ['GET'])]
    public function pdf(
        int $id,
        EntityManagerInterface $em,
        PdfGeneratorInterface $pdfGenerator,
        Request $request
    ): Response {
        $user = $this->getUser();
        if (!$user instanceof \App\Entity\User) {
            throw $this->createAccessDeniedException();
        }

        $cost = $em->getRepository(Cost::class)->findOneForUser($id, $user);
        if (!$cost) {
            throw new NotFoundHttpException();
        }

        $this->denyAccessUnlessGranted(CostVoter::VIEW, $cost);

        $pdf = $pdfGenerator->render('pdf/cost/SHEET.html.twig', [
            'cost' => $cost,
            'locale' => $request->getLocale(),
            'watermark' => '',
        ], [
            'margin-top' => '14mm',
            'margin-bottom' => '14mm',
            'margin-left' => '10mm',
            'margin-right' => '10mm',
            'footer-right' => 'Page [page] / [toPage]',
            'footer-font-size' => 8,
            'footer-spacing' => 8,
            'disable-smart-shrinking' => true,
            'enable-local-file-access' => true,
        ]);

        return new Response($pdf, 200, [
            'Content-Type' => 'application/pdf',
            'Content-Disposition' => sprintf('inline; filename="cost-%s.pdf"', $cost->getCode()),
        ]);
    }
}
